algoritmo "ExemploEnquanto"
var
   contador: inteiro  // Variável de controle do laço
inicio
   contador <- 1  // Inicializa o contador com 1
   // Laço que executa enquanto o contador for menor ou igual a 10
   enquanto contador <= 10 faca
      escreval("Contador: ", contador)  // Exibe o valor do contador
      contador <- contador + 1          // Incrementa o contador em 1
   fimenquanto
fimalgoritmo
